import os
from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain_groq import ChatGroq
from langgraph.prebuilt import create_react_agent

# Import your working Zoho functions!
from zoho_api import get_inventory, adjust_stock

load_dotenv()

# --- 1. Define the Tools ---
# The docstrings ("""...""") are CRITICAL. Groq reads these to understand exactly how and when to use the tool.

@tool
def check_inventory() -> str:
    """Fetches the current inventory of all items in the ERP system. 
    Use this to find item IDs, SKUs, and current stock levels before answering the user."""
    inventory = get_inventory()
    if not inventory:
        return "The inventory is currently empty or could not be reached."
    
    # Format the data nicely for the LLM to read
    result = "Current ERP Inventory:\n"
    for item in inventory:
        result += f"- Name: {item['item_name']} | SKU: {item['sku']} | Stock: {item['stock_on_hand']} | ID: {item['item_id']}\n"
    return result

@tool
def update_inventory(item_id: str, quantity_change: int) -> str:
    """Adjusts the stock level of an item.
    Args:
        item_id: The exact Zoho item_id. YOU MUST USE check_inventory FIRST to find this ID.
        quantity_change: An integer. Use negative numbers to deduct stock (e.g., -2), positive to add.
    """
    success = adjust_stock(item_id, quantity_change, reason="WhatsApp AI Agent Request")
    if success:
        return f"Successfully updated stock for item {item_id} by {quantity_change} units."
    return "Failed to update stock in the ERP system."

# --- 2. Initialize the LLM and Agent ---
# We use Llama 3 8B because it is lightning fast on Groq, perfect for chat.
llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
tools = [check_inventory, update_inventory]

# LangGraph's prebuilt ReAct agent handles all the complex routing automatically
erp_agent = create_react_agent(llm, tools)

def process_chat(user_message: str) -> str:
    """Passes the user message to the agent and extracts the final response."""
    inputs = {"messages": [("user", user_message)]}
    
    # Run the graph
    result = erp_agent.invoke(inputs)
    
    # Return the last message generated by the AI
    return result["messages"][-1].content

# --- TESTING BLOCK ---
if __name__ == "__main__":
    print("Initializing Omni-Channel Agent Brain...\n")
    
    # Test 1: Let the AI read the database
    print("User: 'What is our current stock looking like?'")
    response_1 = process_chat("What is our current stock looking like?")
    print(f"Agent: {response_1}\n")
    
    # Test 2: Let the AI write to the database
    print("User: 'Someone just bought one AI CRM Book. Please deduct it.'")
    response_2 = process_chat("Someone just bought one AI CRM Book. Please deduct 1 from the stock.")
    print(f"Agent: {response_2}\n")